/*
 * generated by Xtext 2.12.0
 */
package org.validation

import java.util.ArrayList
import java.util.HashSet
import java.util.List
import java.util.Set
import org.agriDSL.DesAlternative
import org.agriDSL.DesValueSystemOrPartPair
import org.agriDSL.DesignSpace
import org.agriDSL.DesignSpaceDimension
import org.agriDSL.MeasurementComputeOptimalDesigns
import org.agriDSL.MeasurementRequirementElicitation
import org.agriDSL.Model
import org.agriDSL.Part
import org.agriDSL.PartID
import org.agriDSL.Requirement
import org.agriDSL.SystemID
import org.agriDSL.SystemOrPart
import org.agriDSL.aSystem
import org.eclipse.xtext.validation.Check
import org.generator.AgriDSLGenerator
import org.generator.AgriDSLGeneratorToGraphvizCloneForValidation
import org.generator.CreateLangConstructs
import org.generator.CycleDetection
import org.generator.Stopwatch
import org.generator.dslpaper2.ResolveAExp
import org.generator.dslpaper3.backtracking
import org.agriDSL.FeedbackLoop
import org.eclipse.emf.ecore.EObject
import org.agriDSL.Sensor
import org.agriDSL.Actuator
import org.agriDSL.DefaultSystemExtension
import org.agriDSL.DefaultPartExtension
import org.generator.dslpaper3.ResolveSyntacticSugar
import org.agriDSL.Scenario

class AgriDSLValidator extends AbstractAgriDSLValidator {


	def static String systemsToString (List<aSystem> ss){
		var ret=""
		for(s:ss)
			ret=ret+s.name+","
		return ret
	}
	
	def static String partsToString (List<Part> ps){
		var ret=""
		for(p:ps)
			ret=ret+p.name+","		
		return ret		
	}

	def checkWhetherSensorAndActuatorExist(FeedbackLoop fl, List<Part> ps){
		var Part sensor =   lookupPart(fl.sensorID.head,ps)
		var Part actuator = lookupPart(fl.actuatorID.head,ps)
		if(sensor==null)
			warning("Sensor "+sensor.name+" not found (as a Part) in the model",fl,null)
		if(actuator==null)
			warning("Actuator "+actuator.name+" not found (as a Part) in the model",fl,null)
		if(sensor==null || isSensorOrActuator(sensor)!=1)
			warning("Sensor "+sensor.name+" is not a sensor in the model",fl,null)
		if(actuator==null || isSensorOrActuator(actuator)!=2)
			warning("Actuator "+actuator.name+" is not an actuator in the model",fl,null)
	}

	def static Part lookupPart (String pid, List<Part> ps){
		for(p:ps)
			if(p.name==pid)
				return p
		return null
	}
	
	def static int isSensorOrActuator (Part p){
		if(p.soa.empty) 
			return 0 // neither Sensor, nor Actuator	
		switch(p.soa.head){
			Sensor:   return 1
			Actuator: return 2
		}
	}
	
	@Check // make sure that the scenario consists of unique feedbackloops
	def scenarioConsistsOfUniqueFeedbackloops (Model m){
		var scenarios = m.scen.head
		var sfbl      = scenarios.sfbl
		if(sfbl.size>1)
			for(cnt1:0..sfbl.size-2)
				for(cnt2:cnt1+1..sfbl.size-1)
					if(sfbl.get(cnt1).name.equals(sfbl.get(cnt2).name))
						error("feedbackloop "+sfbl.get(cnt1).name+" occurs more then once in the scenario",m,null)
	}
	
	@Check // make sure that the default extensions are provided to avoid missing values
	def makeSureDefaultSystemAndPartExtensionsAreComplete(Model m){
		var defaultSys  = m.eAllContents.toIterable.filter(typeof(DefaultSystemExtension)).toList.head
		var defaultPart = m.eAllContents.toIterable.filter(typeof(DefaultPartExtension)).toList.head
		
		if(!ResolveSyntacticSugar.systemAndPartExtensionIsComplete (defaultSys.defsysext))
			error("DefaultSystemExtension incomplete!",defaultSys,null)
		if(!ResolveSyntacticSugar.systemAndPartExtensionIsComplete (defaultPart.defparext))
			error("DefaultSystemExtension incomplete!",defaultPart,null)
	}
//ResolveSyntacticSugar.systemAndPartExtensionIsComplete (SystemAndPartExtension sa)
	
	@Check
	def generatePathsForFeedbackLoopViaBacktracking(Model m){
		var mainSystem = m.eAllContents.toIterable.filter(typeof(aSystem)).toList.head
		var systems = m.eAllContents.toIterable.filter(typeof(aSystem)).toList
		var parts = m.eAllContents.toIterable.filter(typeof(Part)).toList
		var feedbackLoops = m.eAllContents.toIterable.filter(typeof(FeedbackLoop)).toList
		var dspace = m.eAllContents.toIterable.filter(typeof(DesignSpace)).head
		var dsm = AgriDSLGenerator.designSpaceDimensionNames(dspace)
		var dsis = CreateLangConstructs.returnDesignInstances(dspace)
		
		for(fl:feedbackLoops){
			checkWhetherSensorAndActuatorExist(fl,parts)
			
			for(dsi:dsis){
				// displays extra information about the feedbackloop, mainly for testing purposes. 
				//testExtraBacktrackingInFormation(mainSystem, systems, parts, dsm, dsi, fl)
				var List<String> cleanFeedbackLoop = backtracking.generateCleanFeedbackloop (fl, mainSystem, systems,  parts, dsm, dsi)
				if(cleanFeedbackLoop!=null)
					info("Clean path from sensor to actuator ( design "+List2String(dsi)+" ): "+cleanFeedbackLoop,fl,null)
			}
		}
	}
	
	def static List2String (List<String> ls) '''«FOR l:ls»«l»_«ENDFOR»'''
	
	def testExtraBacktrackingInFormation(aSystem mainSystem, List<aSystem> systems, List<Part> parts, List<String> dsm, List<String> dsi, FeedbackLoop fl){
		var connections = backtracking.generateConnections(mainSystem,systems,parts,dsm,dsi)
		info("Connections:"+connections,fl,null)
		info ("dsi: "+dsi,fl,null)
		var pathSensor   = backtracking.pathCPStoComponent(mainSystem, systems, parts, fl.sensorID.head, dsm, dsi)
		info("Path from CPS to sensor: "+pathSensor,fl,null)
		var pathActuator = backtracking.pathCPStoComponent(mainSystem, systems, parts, fl.actuatorID.head, dsm, dsi)
		info("Path from CPS to actuator: "+pathActuator,fl,null)
		var feedbackLoop = backtracking.generateFeedbackloop (fl, mainSystem, systems,  parts, dsm, dsi)
		info("Path from sensor to actuator: "+feedbackLoop,fl,null)		
	}

	@Check
	def dimensionsUsedInMeasurementRequirementElicitation(MeasurementRequirementElicitation m){
		var List<String> dims=ResolveAExp.expDimensionsUsed(m)
		var str=""
		for(dim:dims)
			str=str+" "+dim
		info("Dimensions used in the measure:"+str,null)
	}

	@Check
	def multipleMeasurementComputeOptimalDesigns (Model m){
		var measurements=m.eAllContents.toIterable.filter(typeof(MeasurementComputeOptimalDesigns))
		if (measurements.length>1)
			error("Multiple MeasurementComputeOptimalDesigns defined",measurements.head,null)
	}

	//@Check 
	//def executeForTestingPurposes(Model m){ // the following code is not needed for functioning, but inserted for testing only
	//	info("Input validation is currently disabled",m,null) // except for everything above here in the code
	//}

	//@Check
	def allLevel1checks (Model m){ // level 1 input validation (ERRORS)
		//var cpsspec = m.eAllContents.toIterable.filter(typeof(CPSspecification)).toList.head
		var reqs = m.eAllContents.toIterable.filter(typeof(Requirement)).toList
		var dspace = m.eAllContents.toIterable.filter(typeof(DesignSpace)).head
		
		var boolean level1foundErrors = uniqueNamesForSystemsPartsDesalts(m) ||  
						 		        validSystemandPartIDs(m) ||
						 		        eitherMinimumOrMaximumRequirement(reqs) || 
						 		        dSpaceDimNamesUnique(dspace) ||
						 		        dSpaceDimValuesUnique(dspace) ||
						 		        noSystemOrPartreferencesToReferences(m)
						 		        // desAltDefinitions
		
		if(level1foundErrors)
			info("Level 1 input validation active: unique names and references.",null)
		else
			allLevel2checks(m)
	}
	
	def allLevel2checks (Model m){ // level 2 input validation
		//var cpsspec = m.eAllContents.toIterable.filter(typeof(CPSspecification)).toList.head
		var mainSystem = m.eAllContents.toIterable.filter(typeof(aSystem)).toList.head
		var boolean level2foundErrors = cycles(m)
		
		if(level2foundErrors)
			info("Level 2 input validation active: cycle detection.",null)
		else
			allLevel3checks(m)
	}

	//def allLevel3checks (Model m){} // CURRENTLY DISABLED
	// USE WARNINGS IN ADDITION TO INFOS WHEN THE NUMBER DESIGNS THAT MEET A REQUIREMENT IS LOW.

	def allLevel3checks (Model m){ // level 3 input validation
		// maybe add a stopwatch here for responsiveness/concurrency
		//var cpsspec 	  = m.eAllContents.toIterable.filter(typeof(CPSspecification)).toList.head
		var mainSystem    = m.eAllContents.toIterable.filter(typeof(aSystem)).toList.head
		var DSISyspartReq = DSISyspartReq(m)
		
		var boolean level3foundErrors = false // DISABLED!! 
										//displayDSISyspartReq(m, DSISyspartReq) ||
										//displayRequirementsPassed(m, DSISyspartReq)
		
		if(level3foundErrors)
			info("Level 3 input validation active: detailed requirement information",null)
		else
			info("Level 3 input validation passed.",null)
	}

	def String listToString(List<String> ls){
		var ret=""
		for(l:ls)
			ret=ret+l+" "
		return ret
	}
	
	def String listSubSetToString (List<String> ls, int numitems){
		if(ls.length<numitems)
			return listToString(ls)
				
		var ret=""
		for(l:ls.subList(0,numitems))
			ret=ret+l+" "
		ret+ret+" and "+(ls.length-numitems)+" more..."
	}
	
	def displayRequirementsPassed(Model m, List<Pair<String, Pair<String, String>>> DSISyspartReq){
		var mainSystem = m.eAllContents.toIterable.filter(typeof(aSystem)).toList.head
		var reqs       = m.eAllContents.toIterable.filter(typeof(Requirement)).toList
		
		for(r:reqs){
			var Set<String> validDSIs = new HashSet
			for(dsr:DSISyspartReq)
				if(dsr.value.key==mainSystem.name)
					if(dsr.value.value.contains(r.name))
						validDSIs.add(convertDSItoBracketNotation(dsr.key))
			info("Designs meeting requirement: "+listToString(validDSIs.toList),r,null)
		}
		return false // no errors found
	}
	
	// displays for each system and part, which requirements are passed for each design.
	def displayDSISyspartReq(Model m, List<Pair<String, Pair<String, String>>> DSISyspartReq){
		var reqs 			= m.eAllContents.toIterable.filter(typeof(Requirement)).toList
		
		var Set<String> sysparts = new HashSet  // fetch unique sysparts
		for(dsisyspartreq:DSISyspartReq)
			sysparts.add(dsisyspartreq.value.key)
		
		for(s:sysparts){
			for(r:reqs){
				var Set<String> validDSIs = new HashSet
				for(dsr:DSISyspartReq(m))
					if(dsr.value.key==s)
						if(dsr.value.value.contains(r.name)) //TO DO: make this check a bit more thorough
							validDSIs.add(convertDSItoBracketNotation(dsr.key))
				deliverInfoToModelComponent(s,"Req "+r.name+": "+listSubSetToString(validDSIs.toList,10),m)	
			}
			
		}
		return false // no errors found
	}
	
	def String convertDSItoBracketNotation (String dsi){
		var d=dsi
		d=d.substring(1,d.length)
		d="("+d
		d=d.substring(0,d.length-1)
		d=d+")"	
		d.replace("_",",")	
		return d
	}
	
	// returns for each DSI and System+part, which requirements are met
	def List<Pair<String, Pair<String, String>>> DSISyspartReq (Model m) {
		var reqs 		 = m.eAllContents.toIterable.filter(typeof(Requirement)).toList
		var dspace 		 = m.eAllContents.toIterable.filter(typeof(DesignSpace)).head
		var dsm 		 = AgriDSLGenerator.designSpaceDimensionNames(dspace)
		var otherSystems = m.eAllContents.toIterable.filter(typeof(aSystem)).toList.tail.toList
		var parts 		 = m.eAllContents.toIterable.filter(typeof(Part)).toList
		
		var List<Pair<String, Pair<String, String>>> SyspartReq = new ArrayList
		for(dsi:CreateLangConstructs.returnDesignInstances(dspace)){
			var colorGraphString = AgriDSLGeneratorToGraphvizCloneForValidation.trav(reqs, m, dsm, dsi,  otherSystems,  parts,  0, true, true)
			var DSISyspartReq    = AgriDSLGeneratorToGraphvizCloneForValidation.returnDSISyspartReq
			SyspartReq.addAll(DSISyspartReq)
		}
		return SyspartReq
	}
	
	// checks whether no system or part references to references exist
	def noSystemOrPartreferencesToReferences(Model m){
		var boolean errorsFound=false
		var pIDs = m.eAllContents.toIterable.filter(typeof(PartID))
		var sIDs = m.eAllContents.toIterable.filter(typeof(SystemID))
		
		for(p1:pIDs)
			for(p2:pIDs)
				if(p1.partID==p2.name){
					error("Referencing to a reference is not allowed: "+p1,p1,null)
					errorsFound=true
				}
		
		for(s1:sIDs)
			for(s2:sIDs)
				if(s1.systemID==s2.name){
					error("Referencing to a reference is not allowed: "+s1,s1,null)
					errorsFound=true	
				}
		
		return errorsFound
	}
	
	// names of systems, systemsIDs, parts, partIDs and desAlternatives must be unique
	def boolean uniqueNamesForSystemsPartsDesalts(Model m){
		var errorsFound=false
		var List<SystemOrPart> allSystemAndParts = allModelComponents(m)
		for(c1:allSystemAndParts)
			for(c2:allSystemAndParts)
				if(CycleDetection.sysorpartName(c1)==CycleDetection.sysorpartName(c2) && c1!=c2){
					error("Duplicate name found: "+CycleDetection.sysorpartName(c1),c2,null)
					errorsFound=true	
				}
		return errorsFound
	}

	// each abstract system and part should refer to an existing implemented system
	def boolean validSystemandPartIDs (Model m){
		var errorsFound=false
		var List<String> systems =   m.eAllContents.toIterable.filter(typeof(aSystem)).map[system | system.name ].toList
		var List<String> parts = 	 m.eAllContents.toIterable.filter(typeof(Part)).map[part | part.name ].toList
		var pIDs = 	    			 m.eAllContents.toIterable.filter(typeof(PartID))
		var sIDs = 					 m.eAllContents.toIterable.filter(typeof(SystemID))		
		
		for(p:pIDs)
			if(!parts.contains(p.partID)){
				error("Illegal reference to a part: "+p.partID,p,null)
				errorsFound=true
			}

		for(s:sIDs)
			if(!systems.contains(s.systemID)){
				error("Illegal reference to a system: "+s.systemID,s,null)
				errorsFound=true
			}
		return errorsFound		
	}
	
	// check whether the model is free of cycles that can be the result of SystemID and PartID references.
	def cycles (Model m){
		var errorsFound=false
		Stopwatch.init
		Stopwatch.start("inputValidation","cycles")
		for(c:CycleDetection.returnCyclePaths(m)){
			deliverErrorToModelComponent(c.head,"Detected a cycle: "+listOfStringToString(c),m)
			errorsFound=true	
		}
		Stopwatch.stop
		//System.out.println(Stopwatch.entriesToString)
		return errorsFound
	}
	
	def deliverErrorToModelComponent (String component, String message, Model m){
		var List<SystemOrPart> allSystemAndParts = allModelComponents(m)
		for(c:allSystemAndParts)
			if(component==CycleDetection.sysorpartName(c))
				error(message,c,null)
	}
	
	def deliverWarningToModelComponent (String component, String message, Model m){
		var List<SystemOrPart> allSystemAndParts = allModelComponents(m)
		for(c:allSystemAndParts)
			if(component==CycleDetection.sysorpartName(c))
				warning(message,c,null)
	}
	
	def deliverInfoToModelComponent (String component, String message, Model m){
		var List<SystemOrPart> allSystemAndParts = allModelComponents(m)
		for(c:allSystemAndParts)
			if(component==CycleDetection.sysorpartName(c))
				info(message,c,null)
	}
	
	def List<SystemOrPart> allModelComponents (Model m){
		var systems =   m.eAllContents.toIterable.filter(typeof(aSystem))
		var parts = 	m.eAllContents.toIterable.filter(typeof(Part))
		var pIDs = 	    m.eAllContents.toIterable.filter(typeof(PartID))
		var sIDs = 		m.eAllContents.toIterable.filter(typeof(SystemID))
		var desAlts =   m.eAllContents.toIterable.filter(typeof(DesAlternative))
		
		var List<SystemOrPart> allSystemAndParts = new ArrayList
		allSystemAndParts.addAll(systems)
		allSystemAndParts.addAll(parts)
		allSystemAndParts.addAll(pIDs)
		allSystemAndParts.addAll(sIDs)
		allSystemAndParts.addAll(desAlts)
		return allSystemAndParts		
	}
	
	def String listOfStringToString (List<String> los){
		var ret=""
		for(s:los)
			ret=ret+" "+s
		return ret
	}

	// each requirement should have a minimum and/or maximum
	def eitherMinimumOrMaximumRequirement (List<Requirement> rs){
		var boolean foundError=false
		for(r:rs){
			if(r.minReq.isEmpty && r.maxReq.isEmpty){
				error("A requirement should at least either have a minimum or maximum OperationSpace",null)
				foundError=true	
			}
		}
		return foundError 
	}

	// Designspace dimension values should be unique
	def dSpaceDimNamesUnique (DesignSpace ds){
		var boolean foundError=false
		for(dim:ds.DSpaceDimension){
			if(!uniqueValues(dim.value)){
				error("DesignSpaceDimension \""+dim.dsDimensionName+"\" has duplicate value(s)",null)
				foundError=true	
			}
		}
		return foundError
	}
	
	// Designspace dimension names should be unique
	def dSpaceDimValuesUnique (DesignSpace ds){
		var boolean foundError=false
		var dim_names=dSDimToString(ds.DSpaceDimension)
		if(!uniqueValues(dim_names)){
			error("DesignSpaceDimension names are not unique",null)
			foundError=true	
		}
		return foundError
	}	
	

	// TODO: NEEDS FIXING
	/* @Check
	def desAltDefinitions(Model model){
		var desalts = model.eAllContents.toIterable.filter(typeof(DesAlternative)).toList
		var dspace = model.eAllContents.toIterable.filter(typeof(DesignSpace)).toList.head

		for(desalt:desalts){
			var foundDimension=false // the desAlt refers to a (non-existing) dimension
			for(dim:dspace.DSpaceDimension)
				if(dim.dsDimensionName.head==desalt.dsDimensionName.head){ // found the right one, check the values
					foundDimension=true
					if(!similarLists(dim.value,dsValuesToString(desalt.ds)))
						error("DesAlt \""+desalt.dsDimensionName.head+"\" does not have the same values as the DesignSpace ",desalt,null)
					//warning(dim.value+" vs. "+dsValuesToString(desalt.ds),null)
				}
			if(!foundDimension)
				error("DesAlt refers to \""+desalt.dsDimensionName.head+"\", a dimension that does not exist in the DesignSpace",desalt,null)
		}
	}*/
	
	def List<String> dsValuesToString (List<DesValueSystemOrPartPair> das){
		var ret=new ArrayList<String>
		for(da:das)
			ret.add(da.dsValue.head)
		return ret
	}
	
	def List<String> dSDimToString (List<DesignSpaceDimension> das){
		var ret=new ArrayList<String>
		for(da:das)
			ret.add(da.dsDimensionName.head)
		return ret
	}	
	
	def boolean similarLists (List<String> l1, List<String> l2){
		return l1.equals(l2)
	}
	
	def boolean uniqueValues (List<String> vals){
		return (vals.length==vals.clone.toSet.length)
	}
	
	
	/*def valinfo(String s)				{ info(s,null)	}
	def valinfo(String s, EObject o)	{ info(s,o,null) }
	def valwarning(String s)			{ warning(s,null)	}
	def valwarning(String s, EObject o) { warning(s,o,null) }
	def valerror(String s)				{ error(s,null)	}
	def valerror(String s, EObject o)	{ error(s,o,null) }*/
}
